language: node_js
env:
  - DOCKER_COMPOSE_VERSION=1.29.0
python:
  - "3.8"
node_js:
  - 10
before_script:
  - sleep 20
cache:
  - npm
  - pip
script:
  - npm run lint
  - npm run test
  - npm run test-aws
services:
  - docker
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose up -d
  - pip install -U pip
  - pip install awscli-local
  - export AWS_DEFAULT_REGION=us-east-2
  - export AWS_ACCESS_KEY_ID=a
  - export AWS_SECRET_ACCESS_KEY=a
  - awslocal --endpoint-url http://localhost:4566 es create-elasticsearch-domain --domain-name domain-test
