language: node_js
python:
  - "3.8"
node_js:
  - 10
before_script:
  - sleep 20
cache:
  - npm
  - pip
script:
  - npm run lint
  - npm run test
  - npm run test-aws
services:
  - docker
before_install:
  - docker-compose up
  - pip install -U pip
  - pip install awscli-local
  - export AWS_DEFAULT_REGION=us-east-2
  - export AWS_ACCESS_KEY_ID=a
  - export AWS_SECRET_ACCESS_KEY=a
  - aws --endpoint-url http://localhost:4566 es create-elasticsearch-domain --domain-name domain-test
